swagger: "2.0"
info:
  version: "1.0"
  title: "Local Shop Advisor"
  description: Documentazione delle API del progetto del corso di Ingegneria del Software
host: localhost:8080
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /products:
    get:
      summary: Lista di tutti i prodotti
      responses:
        200:
          description: Risposta elaborata correttamente
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
        404:
          description: Error not found
    post:
      summary: Creazione di un nuovo prodotto
      parameters:
        - in: body
          name: product
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        201:
          description: OK
          schema:
            $ref: "#/definitions/Product"
          examples:
            application/json:
              name: Felpa
              description: Una bella felpa
              price: 10
              category: Abbigliamento
              tags:
                - Abbigliamento
                - Felpe
        404:
          description: Error not found
  /products/{productId}:
    get:
      summary: Get di un singolo prodotto
      parameters:
        - in: path
          name: productId
          required: true
          type: string
      responses:
        200:
          description: Risposta elaborata correttamente
          schema:
            $ref: "#/definitions/Product"
        404:
          description: Error not found
    delete:
      summary: Eliminazione di un singolo prodotto
      parameters:
        - in: path
          name: productId
          required: true
          type: string
      responses:
        204:
          description: Prodotto rimosso correttamente
        404:
          description: Error not found
definitions:
  Product:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        minimum: 0
        maximum: 5000
      category:
        type: string
      tags:
        type: array
        items:
          type: string
      #images:
      #  type: array
      #  items:
      #    type: string
    required:
      - name
      - description
      - price
      - category
    example:
      name: Felpa
      description: Una bella felpa
      price: 10
      category: Abbigliamento
      tags:
        - Abbigliamento
        - Felpe
