swagger: "2.0"
info:
  version: "1.0"
  title: "Local Shop Advisor"
  description: Documentazione delle API del progetto del corso di Ingegneria del Software
host: localhost:8080
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/products:
    x-summary: Collezione dei prodotti
    get:
      summary: Lista di tutti i prodotti
      responses:
        200:
          description: Risposta elaborata correttamente
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
          examples:
            application/json:
              - name: Nome
                description: Descrizione
                price: 10
                category: Abbigliamento
                tags: Felpe, Tessuto
                images: null
    post:
      summary: Creazione di un nuovo prodotto
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        201:
          description: ""
          schema:
            $ref: "#/definitions/Product"
          examples:
            application/json:
              name: Nome
              description: Descrizione
              price: 10
              category: Abbigliamento
              tags: Felpe, Tessuto
              images: null
definitions:
  Product:
    title: Product
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        minimum: 0
        maximum: 5000
      category:
        type: string
      tags:
        type: array
        items:
          type: string
      images:
        type: array
        items:
          type: string
    required:
      - name
      - description
      - price
      - category
